#include "PluginEditor.h"
VelvetAudioProcessorEditor::VelvetAudioProcessorEditor(VelvetAudioProcessor& p)
    : AudioProcessorEditor(&p), processorRef(p),
      att_INPUT_GAIN(processorRef.apvts,"INPUT_GAIN",knob_INPUT_GAIN),
      att_COMPRESSOR_THRESHOLD_JYKO(processorRef.apvts,"COMPRESSOR_THRESHOLD_JYKO",knob_COMPRESSOR_THRESHOLD_JYKO),
      att_COMPRESSOR_RATIO_JYKO(processorRef.apvts,"COMPRESSOR_RATIO_JYKO",knob_COMPRESSOR_RATIO_JYKO),
      att_COMPRESSOR_ATTACK_JYKO(processorRef.apvts,"COMPRESSOR_ATTACK_JYKO",knob_COMPRESSOR_ATTACK_JYKO),
      att_COMPRESSOR_RELEASE_JYKO(processorRef.apvts,"COMPRESSOR_RELEASE_JYKO",knob_COMPRESSOR_RELEASE_JYKO),
      att_COMPRESSOR_MAKEUP_JYKO(processorRef.apvts,"COMPRESSOR_MAKEUP_JYKO",knob_COMPRESSOR_MAKEUP_JYKO),
      att_GAIN_GAIN_DB_94SG(processorRef.apvts,"GAIN_GAIN_DB_94SG",knob_GAIN_GAIN_DB_94SG),
      att_REVERB_SIZE_20QI(processorRef.apvts,"REVERB_SIZE_20QI",knob_REVERB_SIZE_20QI),
      att_REVERB_DAMP_20QI(processorRef.apvts,"REVERB_DAMP_20QI",knob_REVERB_DAMP_20QI),
      att_REVERB_MIX_20QI(processorRef.apvts,"REVERB_MIX_20QI",knob_REVERB_MIX_20QI),
      att_BITCRUSHER_BITS_9RFK(processorRef.apvts,"BITCRUSHER_BITS_9RFK",knob_BITCRUSHER_BITS_9RFK),
      att_BITCRUSHER_RATEDIV_9RFK(processorRef.apvts,"BITCRUSHER_RATEDIV_9RFK",knob_BITCRUSHER_RATEDIV_9RFK),
      att_BITCRUSHER_MIX_9RFK(processorRef.apvts,"BITCRUSHER_MIX_9RFK",knob_BITCRUSHER_MIX_9RFK),
      att_FLANGER_RATE_S1OO(processorRef.apvts,"FLANGER_RATE_S1OO",knob_FLANGER_RATE_S1OO),
      att_FLANGER_DEPTH_S1OO(processorRef.apvts,"FLANGER_DEPTH_S1OO",knob_FLANGER_DEPTH_S1OO),
      att_FLANGER_FEEDBACK_S1OO(processorRef.apvts,"FLANGER_FEEDBACK_S1OO",knob_FLANGER_FEEDBACK_S1OO),
      att_FLANGER_MIX_S1OO(processorRef.apvts,"FLANGER_MIX_S1OO",knob_FLANGER_MIX_S1OO),
      att_EXCITER_FREQ_8PKN(processorRef.apvts,"EXCITER_FREQ_8PKN",knob_EXCITER_FREQ_8PKN),
      att_EXCITER_DRIVE_8PKN(processorRef.apvts,"EXCITER_DRIVE_8PKN",knob_EXCITER_DRIVE_8PKN),
      att_EXCITER_MIX_8PKN(processorRef.apvts,"EXCITER_MIX_8PKN",knob_EXCITER_MIX_8PKN),
      att_OUTPUT_GAIN(processorRef.apvts,"OUTPUT_GAIN",knob_OUTPUT_GAIN)
{
    setLookAndFeel(&lnf); setSize(520,724);
    knob_INPUT_GAIN.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_INPUT_GAIN.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_INPUT_GAIN.setLookAndFeel(&lnf); knob_INPUT_GAIN.setDoubleClickReturnValue(true,0.0f); addAndMakeVisible(knob_INPUT_GAIN); lbl_INPUT_GAIN.setText("INPUT",juce::dontSendNotification); lbl_INPUT_GAIN.setJustificationType(juce::Justification::centred); lbl_INPUT_GAIN.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_INPUT_GAIN.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_INPUT_GAIN);
    knob_COMPRESSOR_THRESHOLD_JYKO.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_COMPRESSOR_THRESHOLD_JYKO.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_COMPRESSOR_THRESHOLD_JYKO.setLookAndFeel(&lnf); knob_COMPRESSOR_THRESHOLD_JYKO.setDoubleClickReturnValue(true,-18.0f); addAndMakeVisible(knob_COMPRESSOR_THRESHOLD_JYKO); lbl_COMPRESSOR_THRESHOLD_JYKO.setText("COMPRESSOR THRESHOLD",juce::dontSendNotification); lbl_COMPRESSOR_THRESHOLD_JYKO.setJustificationType(juce::Justification::centred); lbl_COMPRESSOR_THRESHOLD_JYKO.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_COMPRESSOR_THRESHOLD_JYKO.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_COMPRESSOR_THRESHOLD_JYKO);
    knob_COMPRESSOR_RATIO_JYKO.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_COMPRESSOR_RATIO_JYKO.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_COMPRESSOR_RATIO_JYKO.setLookAndFeel(&lnf); knob_COMPRESSOR_RATIO_JYKO.setDoubleClickReturnValue(true,4.0f); addAndMakeVisible(knob_COMPRESSOR_RATIO_JYKO); lbl_COMPRESSOR_RATIO_JYKO.setText("COMPRESSOR RATIO",juce::dontSendNotification); lbl_COMPRESSOR_RATIO_JYKO.setJustificationType(juce::Justification::centred); lbl_COMPRESSOR_RATIO_JYKO.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_COMPRESSOR_RATIO_JYKO.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_COMPRESSOR_RATIO_JYKO);
    knob_COMPRESSOR_ATTACK_JYKO.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_COMPRESSOR_ATTACK_JYKO.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_COMPRESSOR_ATTACK_JYKO.setLookAndFeel(&lnf); knob_COMPRESSOR_ATTACK_JYKO.setDoubleClickReturnValue(true,10.0f); addAndMakeVisible(knob_COMPRESSOR_ATTACK_JYKO); lbl_COMPRESSOR_ATTACK_JYKO.setText("COMPRESSOR ATTACK",juce::dontSendNotification); lbl_COMPRESSOR_ATTACK_JYKO.setJustificationType(juce::Justification::centred); lbl_COMPRESSOR_ATTACK_JYKO.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_COMPRESSOR_ATTACK_JYKO.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_COMPRESSOR_ATTACK_JYKO);
    knob_COMPRESSOR_RELEASE_JYKO.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_COMPRESSOR_RELEASE_JYKO.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_COMPRESSOR_RELEASE_JYKO.setLookAndFeel(&lnf); knob_COMPRESSOR_RELEASE_JYKO.setDoubleClickReturnValue(true,150.0f); addAndMakeVisible(knob_COMPRESSOR_RELEASE_JYKO); lbl_COMPRESSOR_RELEASE_JYKO.setText("COMPRESSOR RELEASE",juce::dontSendNotification); lbl_COMPRESSOR_RELEASE_JYKO.setJustificationType(juce::Justification::centred); lbl_COMPRESSOR_RELEASE_JYKO.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_COMPRESSOR_RELEASE_JYKO.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_COMPRESSOR_RELEASE_JYKO);
    knob_COMPRESSOR_MAKEUP_JYKO.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_COMPRESSOR_MAKEUP_JYKO.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_COMPRESSOR_MAKEUP_JYKO.setLookAndFeel(&lnf); knob_COMPRESSOR_MAKEUP_JYKO.setDoubleClickReturnValue(true,0.0f); addAndMakeVisible(knob_COMPRESSOR_MAKEUP_JYKO); lbl_COMPRESSOR_MAKEUP_JYKO.setText("COMPRESSOR MAKEUP",juce::dontSendNotification); lbl_COMPRESSOR_MAKEUP_JYKO.setJustificationType(juce::Justification::centred); lbl_COMPRESSOR_MAKEUP_JYKO.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_COMPRESSOR_MAKEUP_JYKO.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_COMPRESSOR_MAKEUP_JYKO);
    knob_GAIN_GAIN_DB_94SG.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_GAIN_GAIN_DB_94SG.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_GAIN_GAIN_DB_94SG.setLookAndFeel(&lnf); knob_GAIN_GAIN_DB_94SG.setDoubleClickReturnValue(true,0.0f); addAndMakeVisible(knob_GAIN_GAIN_DB_94SG); lbl_GAIN_GAIN_DB_94SG.setText("GAIN GAIN",juce::dontSendNotification); lbl_GAIN_GAIN_DB_94SG.setJustificationType(juce::Justification::centred); lbl_GAIN_GAIN_DB_94SG.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_GAIN_GAIN_DB_94SG.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_GAIN_GAIN_DB_94SG);
    knob_REVERB_SIZE_20QI.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_REVERB_SIZE_20QI.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_REVERB_SIZE_20QI.setLookAndFeel(&lnf); knob_REVERB_SIZE_20QI.setDoubleClickReturnValue(true,60.0f); addAndMakeVisible(knob_REVERB_SIZE_20QI); lbl_REVERB_SIZE_20QI.setText("REVERB SIZE",juce::dontSendNotification); lbl_REVERB_SIZE_20QI.setJustificationType(juce::Justification::centred); lbl_REVERB_SIZE_20QI.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_REVERB_SIZE_20QI.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_REVERB_SIZE_20QI);
    knob_REVERB_DAMP_20QI.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_REVERB_DAMP_20QI.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_REVERB_DAMP_20QI.setLookAndFeel(&lnf); knob_REVERB_DAMP_20QI.setDoubleClickReturnValue(true,40.0f); addAndMakeVisible(knob_REVERB_DAMP_20QI); lbl_REVERB_DAMP_20QI.setText("REVERB DAMPING",juce::dontSendNotification); lbl_REVERB_DAMP_20QI.setJustificationType(juce::Justification::centred); lbl_REVERB_DAMP_20QI.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_REVERB_DAMP_20QI.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_REVERB_DAMP_20QI);
    knob_REVERB_MIX_20QI.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_REVERB_MIX_20QI.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_REVERB_MIX_20QI.setLookAndFeel(&lnf); knob_REVERB_MIX_20QI.setDoubleClickReturnValue(true,40.0f); addAndMakeVisible(knob_REVERB_MIX_20QI); lbl_REVERB_MIX_20QI.setText("REVERB MIX",juce::dontSendNotification); lbl_REVERB_MIX_20QI.setJustificationType(juce::Justification::centred); lbl_REVERB_MIX_20QI.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_REVERB_MIX_20QI.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_REVERB_MIX_20QI);
    knob_BITCRUSHER_BITS_9RFK.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_BITCRUSHER_BITS_9RFK.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_BITCRUSHER_BITS_9RFK.setLookAndFeel(&lnf); knob_BITCRUSHER_BITS_9RFK.setDoubleClickReturnValue(true,8.0f); addAndMakeVisible(knob_BITCRUSHER_BITS_9RFK); lbl_BITCRUSHER_BITS_9RFK.setText("BIT CRUSH BITS",juce::dontSendNotification); lbl_BITCRUSHER_BITS_9RFK.setJustificationType(juce::Justification::centred); lbl_BITCRUSHER_BITS_9RFK.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_BITCRUSHER_BITS_9RFK.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_BITCRUSHER_BITS_9RFK);
    knob_BITCRUSHER_RATEDIV_9RFK.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_BITCRUSHER_RATEDIV_9RFK.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_BITCRUSHER_RATEDIV_9RFK.setLookAndFeel(&lnf); knob_BITCRUSHER_RATEDIV_9RFK.setDoubleClickReturnValue(true,4.0f); addAndMakeVisible(knob_BITCRUSHER_RATEDIV_9RFK); lbl_BITCRUSHER_RATEDIV_9RFK.setText("BIT CRUSH RATE DIV",juce::dontSendNotification); lbl_BITCRUSHER_RATEDIV_9RFK.setJustificationType(juce::Justification::centred); lbl_BITCRUSHER_RATEDIV_9RFK.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_BITCRUSHER_RATEDIV_9RFK.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_BITCRUSHER_RATEDIV_9RFK);
    knob_BITCRUSHER_MIX_9RFK.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_BITCRUSHER_MIX_9RFK.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_BITCRUSHER_MIX_9RFK.setLookAndFeel(&lnf); knob_BITCRUSHER_MIX_9RFK.setDoubleClickReturnValue(true,80.0f); addAndMakeVisible(knob_BITCRUSHER_MIX_9RFK); lbl_BITCRUSHER_MIX_9RFK.setText("BIT CRUSH MIX",juce::dontSendNotification); lbl_BITCRUSHER_MIX_9RFK.setJustificationType(juce::Justification::centred); lbl_BITCRUSHER_MIX_9RFK.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_BITCRUSHER_MIX_9RFK.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_BITCRUSHER_MIX_9RFK);
    knob_FLANGER_RATE_S1OO.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_FLANGER_RATE_S1OO.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_FLANGER_RATE_S1OO.setLookAndFeel(&lnf); knob_FLANGER_RATE_S1OO.setDoubleClickReturnValue(true,0.5f); addAndMakeVisible(knob_FLANGER_RATE_S1OO); lbl_FLANGER_RATE_S1OO.setText("FLANGER RATE",juce::dontSendNotification); lbl_FLANGER_RATE_S1OO.setJustificationType(juce::Justification::centred); lbl_FLANGER_RATE_S1OO.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_FLANGER_RATE_S1OO.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_FLANGER_RATE_S1OO);
    knob_FLANGER_DEPTH_S1OO.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_FLANGER_DEPTH_S1OO.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_FLANGER_DEPTH_S1OO.setLookAndFeel(&lnf); knob_FLANGER_DEPTH_S1OO.setDoubleClickReturnValue(true,5.0f); addAndMakeVisible(knob_FLANGER_DEPTH_S1OO); lbl_FLANGER_DEPTH_S1OO.setText("FLANGER DEPTH",juce::dontSendNotification); lbl_FLANGER_DEPTH_S1OO.setJustificationType(juce::Justification::centred); lbl_FLANGER_DEPTH_S1OO.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_FLANGER_DEPTH_S1OO.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_FLANGER_DEPTH_S1OO);
    knob_FLANGER_FEEDBACK_S1OO.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_FLANGER_FEEDBACK_S1OO.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_FLANGER_FEEDBACK_S1OO.setLookAndFeel(&lnf); knob_FLANGER_FEEDBACK_S1OO.setDoubleClickReturnValue(true,50.0f); addAndMakeVisible(knob_FLANGER_FEEDBACK_S1OO); lbl_FLANGER_FEEDBACK_S1OO.setText("FLANGER FEEDBACK",juce::dontSendNotification); lbl_FLANGER_FEEDBACK_S1OO.setJustificationType(juce::Justification::centred); lbl_FLANGER_FEEDBACK_S1OO.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_FLANGER_FEEDBACK_S1OO.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_FLANGER_FEEDBACK_S1OO);
    knob_FLANGER_MIX_S1OO.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_FLANGER_MIX_S1OO.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_FLANGER_MIX_S1OO.setLookAndFeel(&lnf); knob_FLANGER_MIX_S1OO.setDoubleClickReturnValue(true,50.0f); addAndMakeVisible(knob_FLANGER_MIX_S1OO); lbl_FLANGER_MIX_S1OO.setText("FLANGER MIX",juce::dontSendNotification); lbl_FLANGER_MIX_S1OO.setJustificationType(juce::Justification::centred); lbl_FLANGER_MIX_S1OO.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_FLANGER_MIX_S1OO.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_FLANGER_MIX_S1OO);
    knob_EXCITER_FREQ_8PKN.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_EXCITER_FREQ_8PKN.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_EXCITER_FREQ_8PKN.setLookAndFeel(&lnf); knob_EXCITER_FREQ_8PKN.setDoubleClickReturnValue(true,5000.0f); addAndMakeVisible(knob_EXCITER_FREQ_8PKN); lbl_EXCITER_FREQ_8PKN.setText("EXCITER FREQ",juce::dontSendNotification); lbl_EXCITER_FREQ_8PKN.setJustificationType(juce::Justification::centred); lbl_EXCITER_FREQ_8PKN.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_EXCITER_FREQ_8PKN.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_EXCITER_FREQ_8PKN);
    knob_EXCITER_DRIVE_8PKN.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_EXCITER_DRIVE_8PKN.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_EXCITER_DRIVE_8PKN.setLookAndFeel(&lnf); knob_EXCITER_DRIVE_8PKN.setDoubleClickReturnValue(true,40.0f); addAndMakeVisible(knob_EXCITER_DRIVE_8PKN); lbl_EXCITER_DRIVE_8PKN.setText("EXCITER DRIVE",juce::dontSendNotification); lbl_EXCITER_DRIVE_8PKN.setJustificationType(juce::Justification::centred); lbl_EXCITER_DRIVE_8PKN.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_EXCITER_DRIVE_8PKN.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_EXCITER_DRIVE_8PKN);
    knob_EXCITER_MIX_8PKN.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_EXCITER_MIX_8PKN.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_EXCITER_MIX_8PKN.setLookAndFeel(&lnf); knob_EXCITER_MIX_8PKN.setDoubleClickReturnValue(true,40.0f); addAndMakeVisible(knob_EXCITER_MIX_8PKN); lbl_EXCITER_MIX_8PKN.setText("EXCITER MIX",juce::dontSendNotification); lbl_EXCITER_MIX_8PKN.setJustificationType(juce::Justification::centred); lbl_EXCITER_MIX_8PKN.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_EXCITER_MIX_8PKN.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_EXCITER_MIX_8PKN);
    knob_OUTPUT_GAIN.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_OUTPUT_GAIN.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_OUTPUT_GAIN.setLookAndFeel(&lnf); knob_OUTPUT_GAIN.setDoubleClickReturnValue(true,0.0f); addAndMakeVisible(knob_OUTPUT_GAIN); lbl_OUTPUT_GAIN.setText("OUTPUT",juce::dontSendNotification); lbl_OUTPUT_GAIN.setJustificationType(juce::Justification::centred); lbl_OUTPUT_GAIN.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_OUTPUT_GAIN.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_OUTPUT_GAIN);
}
VelvetAudioProcessorEditor::~VelvetAudioProcessorEditor() { setLookAndFeel(nullptr); }
void VelvetAudioProcessorEditor::paint(juce::Graphics& g) {
    g.fillAll(juce::Colour(0xff0d1117));
    g.setColour(juce::Colour(0xff161b22)); g.fillRect(0,0,520,44);
    g.setColour(juce::Colour(0xff4d8bff).withAlpha(0.2f)); g.fillRect(0,43,520,1);
    g.setColour(juce::Colour(0xffe8eaf0).withAlpha(0.4f)); g.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),11.0f,juce::Font::bold));
    g.drawText("ARCHERGATE",14,0,520-28,44,juce::Justification::centredLeft,false);
    g.setColour(juce::Colour(0xff4d8bff)); g.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),15.0f,juce::Font::bold));
    g.drawText("VELVET",14,0,520-28,44,juce::Justification::centredRight,false);
}
void VelvetAudioProcessorEditor::resized() {
    knob_INPUT_GAIN.setBounds(24,60,112,86); lbl_INPUT_GAIN.setBounds(20,146,120,14);
    knob_COMPRESSOR_THRESHOLD_JYKO.setBounds(144,60,112,86); lbl_COMPRESSOR_THRESHOLD_JYKO.setBounds(140,146,120,14);
    knob_COMPRESSOR_RATIO_JYKO.setBounds(264,60,112,86); lbl_COMPRESSOR_RATIO_JYKO.setBounds(260,146,120,14);
    knob_COMPRESSOR_ATTACK_JYKO.setBounds(384,60,112,86); lbl_COMPRESSOR_ATTACK_JYKO.setBounds(380,146,120,14);
    knob_COMPRESSOR_RELEASE_JYKO.setBounds(24,168,112,86); lbl_COMPRESSOR_RELEASE_JYKO.setBounds(20,254,120,14);
    knob_COMPRESSOR_MAKEUP_JYKO.setBounds(144,168,112,86); lbl_COMPRESSOR_MAKEUP_JYKO.setBounds(140,254,120,14);
    knob_GAIN_GAIN_DB_94SG.setBounds(264,168,112,86); lbl_GAIN_GAIN_DB_94SG.setBounds(260,254,120,14);
    knob_REVERB_SIZE_20QI.setBounds(384,168,112,86); lbl_REVERB_SIZE_20QI.setBounds(380,254,120,14);
    knob_REVERB_DAMP_20QI.setBounds(24,276,112,86); lbl_REVERB_DAMP_20QI.setBounds(20,362,120,14);
    knob_REVERB_MIX_20QI.setBounds(144,276,112,86); lbl_REVERB_MIX_20QI.setBounds(140,362,120,14);
    knob_BITCRUSHER_BITS_9RFK.setBounds(264,276,112,86); lbl_BITCRUSHER_BITS_9RFK.setBounds(260,362,120,14);
    knob_BITCRUSHER_RATEDIV_9RFK.setBounds(384,276,112,86); lbl_BITCRUSHER_RATEDIV_9RFK.setBounds(380,362,120,14);
    knob_BITCRUSHER_MIX_9RFK.setBounds(24,384,112,86); lbl_BITCRUSHER_MIX_9RFK.setBounds(20,470,120,14);
    knob_FLANGER_RATE_S1OO.setBounds(144,384,112,86); lbl_FLANGER_RATE_S1OO.setBounds(140,470,120,14);
    knob_FLANGER_DEPTH_S1OO.setBounds(264,384,112,86); lbl_FLANGER_DEPTH_S1OO.setBounds(260,470,120,14);
    knob_FLANGER_FEEDBACK_S1OO.setBounds(384,384,112,86); lbl_FLANGER_FEEDBACK_S1OO.setBounds(380,470,120,14);
    knob_FLANGER_MIX_S1OO.setBounds(24,492,112,86); lbl_FLANGER_MIX_S1OO.setBounds(20,578,120,14);
    knob_EXCITER_FREQ_8PKN.setBounds(144,492,112,86); lbl_EXCITER_FREQ_8PKN.setBounds(140,578,120,14);
    knob_EXCITER_DRIVE_8PKN.setBounds(264,492,112,86); lbl_EXCITER_DRIVE_8PKN.setBounds(260,578,120,14);
    knob_EXCITER_MIX_8PKN.setBounds(384,492,112,86); lbl_EXCITER_MIX_8PKN.setBounds(380,578,120,14);
    knob_OUTPUT_GAIN.setBounds(24,600,112,86); lbl_OUTPUT_GAIN.setBounds(20,686,120,14);
}
